version: '2'

services:
    client:
      build: client/src
      ports:
          - "3020:3020"
      depends_on:
          - server

    server:
      build: server/
      ports:
          - "3021:3021"
      depends_on:
          - database

    database:
      image: mongo
      ports:
          - "27017:27017"

